services:
  web:
    image: webdevops/php-apache:8.4
    ports:
      - "8080:80"
    volumes:
      # Mount the entire project for live code changes
      - .:/var/www/html
      # Keep uploads and sessions as separate volumes
      - session_data:/tmp/php_sessions
    depends_on:
      - db
    environment:
      - DOCKER_ENV=true
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: storageunit
      MYSQL_USER: storageuser
      MYSQL_PASSWORD: storagepass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      PMA_ARBITRARY: 1
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
  session_data: